apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: avdzee2dl-go
  janus-idp.io/tekton: avdzee2dl-go
  backstage.io/kubernetes-id: avdzee2dl-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: avdzee2dl-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
