apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avdzee2dl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avdzee2dl-go 
  name: avdzee2dl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: avdzee2dl-go 
